name: OpenCV Project Docker Image CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-24.04

    env:
      IMAGE_NAME: myopencv_image:latest
      # optionally pin OpenCV version here
      # OPENCV_VERSION: "4.9.0"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Optional: Debug workspace content
      - name: List contents of the repository
        run: ls -la

      - name: Build the Docker image
        run: |
          docker build \
            --build-arg OPENCV_VERSION=${OPENCV_VERSION} \
            -t $IMAGE_NAME .

      - name: Configure CMake
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/OpenCVProjects \
            $IMAGE_NAME \
            cmake -S /OpenCVProjects -B /OpenCVProjects/build -DCMAKE_BUILD_TYPE=Release

      - name: Build with CMake
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/OpenCVProjects \
            $IMAGE_NAME \
            cmake --build /OpenCVProjects/build --config Release

      # Uncomment to run tests if you have them
      # - name: Run tests
      #   run: |
      #     docker run --rm \
      #       -v ${{ github.workspace }}:/OpenCVProjects \
      #       $IMAGE_NAME \
      #       ctest --test-dir /OpenCVProjects/build --output-on-failure


# Optionally verify OpenCV version
# RUN python3 -c "import cv2; print(cv2.__version__)"
